# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a7e3525beb3d40c3886f429c9d9f6449f24ad331fd0269687a0fc05f87bfee4703ea1739510e4d64024a854d2a5e72d0f5440a486d587835eb0dda3b7dc676e4

test:
  secret_key_base: c4033934ed129e7a9e819da5be29c15bf3618432c727abdfa04aaeb00b7c92f8407395caa309d9cfb6bcc146b342b88317dc915247bd465779a4b730c640cf5f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
